### ISSUE TITLE
Drag is broken if text has a tspan with X attribute set

### ISSUE THREAD

**Issue by eugene-rozov** [svgdotjs/svg.draggable.js#133] opened 2021-08-28 21:16 UTC
Drag is broken if the text element has a tspan with manually set X attribute. Here is a [sample](https://codepen.io/nazica/pen/powjdEB) — try to drag a rectangle and you see it starts to go off with acceleration while tspan element is not moving using X axis.

Behavior is somewhat similar to [this issue](https://github.com/svgdotjs/svg.draggable.js/issues/132).

**Comment by Glandos** [comment] 2021-11-05 13:23
This is maybe caused by the fact that `move` will set `x` and `y` for each child instead of setting a `transform` on the parent, as mentioned in svgdotjs/svg.js/issues/1110

Draggable should have an option to use translate instead of move. For now, I use:
```js
element.on('dragmove.namespace', e => {
    const { handler, box } = e.detail
    e.preventDefault()
    handler.el.translate(box.x, box.y)
})
```

**Comment by Fuzzyma** [comment] 2024-06-27 04:53
This issue is fixed in newer versions of svg.js

**Closed by Fuzzyma** 2024-06-27 04:53 UTC
